import "server-only";
import { asc } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/server/db/client";
import { auditEvents, campaigns, draftRequests, emailTemplateVersions, emailTemplates, outlookDraftRefs } from "@/server/db/schema";
const templateSchema = z.object({ name: z.string().trim().min(2), category: z.string().trim().min(2), subject: z.string().trim().min(1), body: z.string().trim().min(1) });
export async function createTemplate(input: unknown, userId: string) { const data = templateSchema.parse(input); return getDb().transaction(async (tx) => { const [template] = await tx.insert(emailTemplates).values({ name: data.name, category: data.category }).returning(); await tx.insert(emailTemplateVersions).values({ templateId: template.id, version: 1, subject: data.subject, body: data.body }); await tx.insert(auditEvents).values({ actorUserId: userId, eventType: "template.created", metadata: { templateId: template.id } }); return template; }); }
export async function listTemplates() { return getDb().select().from(emailTemplates).orderBy(asc(emailTemplates.name)); }
export async function createCampaign(name: string, objective: string | undefined, templateId: string | undefined, userId: string) { const [campaign] = await getDb().insert(campaigns).values({ name, objective: objective || null, templateId: templateId || null }).returning(); await getDb().insert(auditEvents).values({ actorUserId: userId, eventType: "campaign.created", metadata: { campaignId: campaign.id } }); return campaign; }
export async function createDraft(recipient: string, subject: string, body: string, userId: string) { const composeUrl = `https://outlook.office.com/mail/deeplink/compose?to=${encodeURIComponent(recipient)}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; return getDb().transaction(async (tx) => { const [draft] = await tx.insert(draftRequests).values({ recipient, subject, body, status: "reviewed" }).returning(); await tx.insert(outlookDraftRefs).values({ draftRequestId: draft.id, composeUrl }); await tx.insert(auditEvents).values({ actorUserId: userId, eventType: "draft.prepared", metadata: { draftRequestId: draft.id } }); return { draft, composeUrl }; }); }
