import "server-only";
import { and, asc, eq, isNull, like } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/server/db/client";
import { auditEvents, duplicateCandidates, duplicateReviews, prospectInterestHistory, prospectScoreFactors, prospectScoreSnapshots, prospectStageHistory, prospects, recruitingCycles, schools } from "@/server/db/schema";
import { normaliseName } from "@/server/crm/validation";
const stages = ["new_lead", "contacted", "engaged", "visit_scheduled", "audition_planned", "audition_completed", "applied", "admitted", "scholarship_offered", "committed", "enrolled"] as const;
const interests = ["hot", "warm", "cool", "inactive"] as const;
const createSchema = z.object({ fullName: z.string().trim().min(2), schoolId: z.string().uuid().optional(), cycleId: z.string().uuid(), source: z.string().trim().min(2), stage: z.enum(stages).default("new_lead"), interest: z.enum(interests).default("cool") });
export async function listCycles() { return getDb().select().from(recruitingCycles).where(isNull(recruitingCycles.archivedAt)).orderBy(asc(recruitingCycles.entryTerm)); }
export async function createCycle(name: string, entryTerm: string, userId: string) { const [cycle] = await getDb().insert(recruitingCycles).values({ name, entryTerm }).returning(); await getDb().insert(auditEvents).values({ actorUserId: userId, eventType: "cycle.created", metadata: { cycleId: cycle.id } }); return cycle; }
export async function createProspect(input: unknown, userId: string) { const data = createSchema.parse(input); const db = getDb(); return db.transaction(async (tx) => { const normalizedName = normaliseName(data.fullName); const [prospect] = await tx.insert(prospects).values({ fullName: data.fullName, normalizedName, schoolId: data.schoolId || null, recruitingCycleId: data.cycleId, source: data.source, stage: data.stage, interestLevel: data.interest }).returning(); await tx.insert(prospectStageHistory).values({ prospectId: prospect.id, stage: data.stage, changedByUserId: userId }); await tx.insert(prospectInterestHistory).values({ prospectId: prospect.id, interestLevel: data.interest, changedByUserId: userId }); const matches = await tx.select({ id: prospects.id }).from(prospects).where(and(eq(prospects.normalizedName, normalizedName), eq(prospects.recruitingCycleId, data.cycleId))).limit(10); for (const match of matches) if (match.id !== prospect.id) await tx.insert(duplicateCandidates).values({ prospectId: prospect.id, candidateProspectId: match.id, reason: "matching name and recruiting cycle" }).onConflictDoNothing(); await tx.insert(auditEvents).values({ actorUserId: userId, eventType: "prospect.created", metadata: { prospectId: prospect.id } }); return prospect; }); }
export async function listProspects(q = "") { return getDb().select({ prospect: prospects, school: schools, cycle: recruitingCycles }).from(prospects).leftJoin(schools, eq(prospects.schoolId, schools.id)).innerJoin(recruitingCycles, eq(prospects.recruitingCycleId, recruitingCycles.id)).where(and(isNull(prospects.archivedAt), q ? like(prospects.normalizedName, `%${normaliseName(q)}%`) : undefined)).orderBy(asc(prospects.fullName)); }
export async function changeStage(id: string, stage: (typeof stages)[number], userId: string, note?: string) { await getDb().transaction(async (tx) => { await tx.update(prospects).set({ stage, updatedAt: new Date() }).where(eq(prospects.id, id)); await tx.insert(prospectStageHistory).values({ prospectId: id, stage, note, changedByUserId: userId }); await tx.insert(auditEvents).values({ actorUserId: userId, eventType: "prospect.stage_changed", metadata: { id, stage } }); }); }
export async function scoreProspect(id: string) { const [prospect] = await getDb().select().from(prospects).where(eq(prospects.id, id)).limit(1); if (!prospect) throw new Error("Prospect not found."); const factors = [{ factor: "pipeline_stage", contribution: stages.indexOf(prospect.stage as (typeof stages)[number]) * 8, rationale: `Stage: ${prospect.stage}` }, { factor: "interest", contribution: ({ hot: 25, warm: 15, cool: 5, inactive: -10 } as Record<string, number>)[prospect.interestLevel] ?? 0, rationale: `Interest: ${prospect.interestLevel}` }]; const missing = prospect.schoolId ? [] : ["school"]; const total = Math.max(0, Math.min(100, factors.reduce((sum, factor) => sum + factor.contribution, 0))); const [snapshot] = await getDb().insert(prospectScoreSnapshots).values({ prospectId: id, totalScore: total, missingData: missing }).returning(); await getDb().insert(prospectScoreFactors).values(factors.map((factor) => ({ snapshotId: snapshot.id, ...factor }))); return snapshot; }
export async function getProspect(id: string) { const db = getDb(); const [prospect] = await db.select({ prospect: prospects, school: schools, cycle: recruitingCycles }).from(prospects).leftJoin(schools, eq(prospects.schoolId, schools.id)).innerJoin(recruitingCycles, eq(prospects.recruitingCycleId, recruitingCycles.id)).where(eq(prospects.id, id)).limit(1); if (!prospect) return null; const history = await db.select().from(prospectStageHistory).where(eq(prospectStageHistory.prospectId, id)).orderBy(asc(prospectStageHistory.createdAt)); const [score] = await db.select().from(prospectScoreSnapshots).where(eq(prospectScoreSnapshots.prospectId, id)).orderBy(asc(prospectScoreSnapshots.calculatedAt)); return { ...prospect, history, score }; }
export async function listDuplicateCandidates() { return getDb().select({ candidate: duplicateCandidates, prospect: prospects }).from(duplicateCandidates).innerJoin(prospects, eq(duplicateCandidates.prospectId, prospects.id)).where(eq(duplicateCandidates.status, "pending")); }
export async function reviewDuplicate(candidateId: string, decision: "not_duplicate" | "needs_review", userId: string, note?: string) { await getDb().transaction(async (tx) => { await tx.update(duplicateCandidates).set({ status: decision }).where(eq(duplicateCandidates.id, candidateId)); await tx.insert(duplicateReviews).values({ candidateId, reviewerUserId: userId, decision, note: note || null }); await tx.insert(auditEvents).values({ actorUserId: userId, eventType: "prospect.duplicate_reviewed", metadata: { candidateId, decision } }); }); }
export { stages, interests };
