import Link from "next/link";
import { listImportBatches } from "@/server/imports/service";
import { stageImportAction } from "./actions";
export default async function ImportsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [batches, params] = await Promise.all([listImportBatches(), searchParams]);
  return <section className="max-w-5xl"><p className="mb-2 text-sm font-bold tracking-wider text-[var(--purple)]">PHASE 2</p><h1 className="text-3xl font-bold">Imports</h1><p className="mt-2 max-w-3xl text-[var(--muted)]">Files are stored immutably in staging. Review proposals before any future live-record action; this phase never writes schools or directors.</p>
    {params.error === "stage_failed" && <p role="alert" className="mt-4 rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">We couldn’t stage that file. The safe error details were recorded for diagnosis; please try again after the fix is deployed.</p>}
    <form action={stageImportAction} className="mt-6 grid gap-3 rounded-lg border border-[var(--border)] bg-white p-5"><label htmlFor="file" className="font-semibold">Stage an Excel or CSV file</label><input id="file" name="file" type="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" required className="block w-full cursor-pointer rounded-md border border-[var(--border)] bg-white text-sm text-[var(--muted)] file:mr-3 file:cursor-pointer file:rounded-l-md file:border-0 file:bg-[var(--purple)] file:px-4 file:py-2 file:font-semibold file:text-white hover:file:bg-[var(--purple-dark)] focus:outline-none focus:ring-2 focus:ring-[var(--purple)]"/><p className="text-sm text-[var(--muted)]">Choose file to select an Excel or CSV file (maximum 10 MB). Uploads are saved with a SHA-256 hash and every source cell.</p><button className="w-fit rounded-md bg-[var(--purple)] px-4 py-2 font-semibold text-white hover:bg-[var(--purple-dark)]">Stage for review</button></form>
    <h2 className="mt-8 text-lg font-bold">Import batches</h2><div className="mt-3 overflow-x-auto rounded-lg border border-[var(--border)] bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[var(--muted)]"><tr><th className="px-4 py-3">File</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Created</th><th className="px-4 py-3"><span className="sr-only">Review</span></th></tr></thead><tbody>{batches.length ? batches.map((batch) => <tr key={batch.id} className="border-t border-[var(--border)]"><td className="px-4 py-3 font-medium">{batch.sourceFilename}</td><td className="px-4 py-3">{batch.status}</td><td className="px-4 py-3">{batch.createdAt.toLocaleString()}</td><td className="px-4 py-3"><Link className="font-semibold text-[var(--purple)] underline" href={`/imports/${batch.id}`}>Review</Link></td></tr>) : <tr><td colSpan={4} className="px-4 py-5 text-[var(--muted)]">No staged imports yet.</td></tr>}</tbody></table></div></section>;
}
