import Link from "next/link";
import { notFound } from "next/navigation";
import { z } from "zod";
import { getImportBatch } from "@/server/imports/review-service";
import { reviewProposalAction } from "../actions";
const idSchema = z.string().uuid();
export default async function ImportReviewPage({ params }: { params: Promise<{ batchId: string }> }) {
  const { batchId } = await params; if (!idSchema.safeParse(batchId).success) notFound();
  const result = await getImportBatch(batchId); if (!result) notFound(); const { batch, proposals } = result;
  return <section className="max-w-6xl"><Link href="/imports" className="font-semibold text-[var(--purple)] underline">← Imports</Link><p className="mt-5 text-sm font-bold tracking-wider text-[var(--purple)]">PHASE 2 REVIEW</p><h1 className="text-3xl font-bold">{batch.sourceFilename}</h1><p className="mt-2 text-[var(--muted)]">Status: {batch.status}. Decisions are audited but do not create or update live records in this phase.</p><div className="mt-6 grid gap-4">{proposals.map((proposal) => <article key={proposal.id} className="rounded-lg border border-[var(--border)] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold capitalize">{proposal.entityType} · {proposal.proposedAction}</h2><span className="rounded bg-slate-100 px-2 py-1 text-xs font-semibold uppercase">{proposal.status}</span></div><pre className="mt-3 overflow-x-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(proposal.payload, null, 2)}</pre>{proposal.status === "pending" && <form action={reviewProposalAction} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="proposalId" value={proposal.id}/><input name="note" aria-label="Review note" placeholder="Optional review note" className="min-w-48 rounded border border-[var(--border)] px-2 py-1 text-sm"/><button name="decision" value="approved" className="rounded bg-[var(--purple)] px-3 py-1.5 text-sm font-semibold text-white">Approve proposal</button><button name="decision" value="rejected" className="rounded border border-[var(--border)] px-3 py-1.5 text-sm font-semibold">Reject</button></form>}</article>)}</div></section>;
}
